server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka-0:9092,kafka-1:9092,kafka-2:9092

    # Producer settings
    producer:
      acks: all
      retries: 3
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="producer-secret";

    # Consumer settings
    consumer:
      auto-offset-reset: earliest
      group-id: secure-processor-id
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="consumer" password="consumer-secret";

    # SSL settings
    ssl:
      trust-store-location: file:kafka-certs/kafka.truststore.jks
      trust-store-password: password
      key-store-location: file:kafka-certs/kafka.keystore.jks
      key-store-password: password
      key-password: password

    # Admin client settings
    admin:
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";